### ISSUE TITLE
Python API setup.py does not list requirements 

### ISSUE THREAD

**Issue by rly** [laboratorybox/labbox-ephys#110] opened 2020-10-28 19:14 UTC
In order to import labbox_ephys, the following packages need to be installed:
- kachery_p2p
- numpy
- spikeextractors
- scipy
- h5py
- hither

These requirements should be listed in `setup.py`. 

For context, I am coming here from running https://github.com/LorenFrankLab/nwb_datajoint/ which imports `labbox_ephys` and references `labbox_ephys.prepare_snippets_h5_from_extractors`

**Comment by magland** [comment] 2020-10-28 19:53
I think we can add those requirements. However, I will mention that the software is meant to be run inside a container, and there is a vscode .devcontainer that takes care of all the prerequisites.

@jsoules

**Comment by jsoules** [comment] 2020-12-04 14:43
To reproduce:

1. Create new Conda environment with no dependencies (`conda create --name labbox-import-test python=3.8`) and activate it (`conda activate labbox-import-test`)
2. Get up-to-date copy of labbox source and install locally (`cd labbox-ephys/python && pip install -e .`)
3. Attempt to import labbox in interactive script (as in https://gist.github.com/magland/e01d114cd8e54029dfc7402cf50ce0cf#file-import-franklab-example-py): (in python terminal) `import labbox_ephys as le`)

Result:
import fails, listing various modules which are not available.

Fix:
Discovered minimal set of requirements by iteratively updating `setup.py`, re-installing labbox in the test conda environment, and then attempting import.
Looks like hither installs kachery, so I've left that one out.

**Comment by jsoules** [comment] 2020-12-04 16:26
Closed by PR #134

**Closed by jsoules** 2020-12-04 16:26 UTC
